### ISSUE TITLE
Diff is always one line longer than it should be

### ISSUE THREAD

**Issue by cmeeren** [deviousasti/fsharp-formatting-for-vs#13]
Before:

![image](https://user-images.githubusercontent.com/7766733/106369022-6d764b00-634e-11eb-9234-3e55174880f1.png)

After:

![image](https://user-images.githubusercontent.com/7766733/106369026-7404c280-634e-11eb-8d20-553c5a4e7205.png)

As you can see, the diff indicates that the next line was also changed. I guess this has something to do with how newlines are included/applied as part of the diff. This is not a problem for this specific example, but can in many other cases lead you on a wild goose chase trying to find out what was changed on some lines where nothing was changed.

**Comment by deviousasti** [comment]
Yes, this was on my to-do list. 
It mostly has to do with diff-patching in Visual Studio.

https://github.com/deviousasti/fsharp-formatting-for-vs/blob/26d43ea3334313459e5c90d5fc64b513d2418313/src/FantomasHandler.cs#L122

This would ideally be a candidate for `Replace` instead of `Delete+Insert` which works, but figuring that out in an elegant way might be hard. I haven't spent too much time on it.

**Comment by cmeeren** [comment]
Might it be so simple that you trim a single newline (`\r\n` or `\n`) from `oldText` and `newText` (if both end with the same type of newline)?

**Comment by deviousasti** [comment]
Hi, sorry about the delay in responding.
There's a set of deletes followed by a set of inserts. It's not easy to decide if a line has been truly removed, only for it to be put back. Fantomas sometimes deletes several lines worth of whitespace in one go. I'm mostly worried about edge cases which could crop up and eat someone's code.

Would you be interested in solving this with me in live-share?

**Comment by cmeeren** [comment]
No worries about the delay, it's not like I'm a paying customer of a service 😅

I appreciate the invitation, but unfortunately I'm already at 120% capacity at the moment, and I think it'll stay that way for a while. 😩

**Comment by deviousasti** [comment]
My sympathies.

**Comment by deviousasti** [comment]
Hi @cmeeren 
I've implemented diff shrinking, so now the edit surface should be minimal.

Could you please update the extension and try it out?

**Comment by cmeeren** [comment]
Works excellently, thanks a lot! 🙌
