### ISSUE TITLE
Bump to Fantomas 4.4

### ISSUE THREAD

**Issue by asik** [deviousasti/fsharp-formatting-for-vs#15]
Just a friendly reminder that Fantomas 4.4 stable is out and we would like to update as soon as possible :)

**Comment by deviousasti** [comment]
Hi @asik,

I was trying to build a release with FCS 39, and there are just too many breaking changes with 4.4 for it to work right now. 
I've released a stable release of 4.4 now.

The extension should auto-update now. 

Cheers.
