### ISSUE TITLE
Support VS2022

### ISSUE THREAD

**Issue by TiraelSedai** [deviousasti/fsharp-formatting-for-vs#16]
I don't have much to add, Visual Studio 2022 support would be nice.

**Comment by deviousasti** [comment]
Thanks you for the reminder. I need to get around to installing VS '22! 
This hopefully won't be a major change and might just be a few configuration changes. VSSDK sure is vast and mysterious.

**Comment by kxxt** [comment]
For those who don't want to wait, I've built one for Visual Studio 2022 which you can use until the official one get released.

The extension seems just working fine. Howerer please do note that this is an **unofficial** prerelease.

My forked repo: https://github.com/kxxt/fsharp-formatting-for-vs/
Unofficial prerelease: https://github.com/kxxt/fsharp-formatting-for-vs/releases/tag/v0.9.1-pre-vs2022

**Comment by deviousasti** [comment]
@kxxt The fork seems to be even with master.
Could you push your changes?

**Comment by kxxt** [comment]
> @kxxt The fork seems to be even with master.
> Could you push your changes?

Just switch to branch `vs2022` and you can see the changes.

(I don't think it's suitable for opening a pull request)

**Comment by kxxt** [comment]
> (I don't think it's suitable for opening a pull request)

My commit changed the package versions to preview and changed target architecture to `amd64`, which makes 32bit Visual Studio 2019 incompatible.

Here is the tidy way to support both 2019 and 2022 (The structure of the project needs to be changed): https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022

**Comment by deviousasti** [comment]
I can't a multi-targeting project to build.
Mads' own extensions was updated in a non backward-compatible way.
https://github.com/madskristensen/DialToolsForVS/pull/38/files

**Comment by kxxt** [comment]
I managed to make it work 😄 . See #19.
