### ISSUE TITLE
Editorconfig

### ISSUE THREAD

**Issue by nojaf** [deviousasti/fsharp-formatting-for-vs#2]
Earlier this week support for .editorconfig files was added.
You can get the settings by using [CodeFormatter.ReadConfiguration](https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/CodeFormatter.fsi#L38)
Simply pass the current fsharp file as a parameter to get the settings.

You will, of course, need to make a decision about what to do with the settings from the UI.

**Comment by deviousasti** [comment]
I've added Fantomas as a submodule and made it build against fantomas/master.
Would still need some kind of fallback if there's no `.editorconfig` for the project, so maybe keep the VS settings as is?
 Should I wait for it to stabilize before implementing?

From the spec:

> When opening a file, EditorConfig plugins look for a file named .editorconfig in the directory of the opened file and in every parent directory. A search for .editorconfig files will stop if the root filepath is reached or an EditorConfig file with root=true is found.
> 
> EditorConfig files are read top to bottom and the most recent rules found take precedence. Properties from matching EditorConfig sections are applied in the order they were read, so properties in closer files take precedence.

The config files are supposed to cascade. The API seems to load from a single file.
Will this be handled by the `ReadConfiguration` in the future?

**Comment by nojaf** [comment]
The only thing that could still somewhat change is some setting names when it comes to .editorconfig.
The public API should be stable but I understand if you'd like to wait sometime before implementing this.

If you have no editor config files in your project using ReadConfiguration will fallback to the default config.
Internally we use https://github.com/editorconfig/editorconfig-core-net to collect the settings.
When you pass any file there, it will look for editorconfig files (in the same folder and parent folders) until the root file is detected.
Within an editorconfig file you can have certain glob expressions and filter files. (For example only apply settings to *.fsi or !ignoreThisFile.fsx)
That is why you start looking from the point of view of the target file and not from the configuration file.

**Comment by deviousasti** [comment]
Thanks. That makes a lot of sense.
It would be nice to know if there were any editor config settings to be found to use the user-profile defaults.

Is something like this acceptable?

```
let readConfiguration (fsharpFile:string) : FormatConfig option =
    let editorConfigSettings: Fantomas.EditorConfig.Core.FileConfiguration = editorConfigParser.Parse(fileName = fsharpFile)
    if editorConfigSettings.Properties.Count = 0 then
        None
    else
        Some <| EditorConfig.parseOptionsFromEditorConfig editorConfigSettings
```

**Comment by nojaf** [comment]
I think you could just check if something changed by comparing to the default settings.
```fsharp
let userSettings = CodeFormatter.ReadConfig("someFile.fs")
let hasChanges = userSettings <> FormatConfig.Default
```

**Comment by deviousasti** [comment]
I did think of this, but it's a false positive when the editor config matches with the defaults.

**Comment by nojaf** [comment]
Ah I see, you would like to detect whether the editorconfig or the UI settings should be used by this check?
Yeah then returning a FormatConfig option makes sense.
Hmm, maybe it could be useful to have this as part of the public API to return the option.

**Comment by deviousasti** [comment]
I'm trying to make the experience a familiar one to C# devs, so we can get more converts. 😈 
If you don't want a surface change, what about

```
static member ReadConfiguration : string -> FormatConfig
static member TryReadConfiguration : string -> FormatConfig option
```
I can submit a PR based on what you decide.

**Comment by nojaf** [comment]
Since Fantomas is still in alpha it ok to have breaking api changes.
I like your suggestion, best of both worlds.

**Comment by deviousasti** [comment]
With that PR in, I've added support for `.editorconfig` with [bf6eca9f](https://github.com/deviousasti/fsharp-formatting-for-vs/commit/bf6eca9f6b0434a02d55791689153e0fcfa4fc97).

**Comment by nojaf** [comment]
Many thanks for this!

**Comment by deviousasti** [comment]
https://twitter.com/jordan_n_marr/status/1285225997911183361

Keeping formatting settings in was worth the effort. :)
I guess it's the first point of discovery.
