### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by brettrowberry** [deviousasti/fsharp-formatting-for-vs#3]
Having a license would make it clear that I can adopt this at work. Thanks!

**Comment by deviousasti** [comment]
Well, since this in in early stages, what would you prefer? 😁 
I usually use MIT.

**Comment by brettrowberry** [comment]
Fantomas itself uses https://github.com/fsprojects/fantomas/blob/master/LICENSE.md. Perhaps they should match? @nojaf?

**Comment by deviousasti** [comment]
MIT is equivalent to Apache but with much less lawyerese. 
Let's go with that then.

**Comment by deviousasti** [comment]
Added the MIT license [04c3fca9](https://github.com/deviousasti/fsharp-formatting-for-vs/commit/04c3fca97aae0e25aba9638a55a8062410f1b528). Published version 0.4 to the marketplace.

**Comment by nojaf** [comment]
I think MIT is fine here, less hassle indeed.

**Comment by brettrowberry** [comment]
I was actually thinking of a LICENSE file at the root of the repo! This is even better! Could the same file be used in both places?

**Comment by deviousasti** [comment]
My thinking was, considering the folder structure, the licenses for the sources would be covered by:
```
fantomas/license.txt
src/license.txt
```
I have now added this fact to the Readme.

**Comment by brettrowberry** [comment]
Amazing!
