### ISSUE TITLE
Format all documents

### ISSUE THREAD

**Issue by brettrowberry** [deviousasti/fsharp-formatting-for-vs#4]
I can format an individual document. Is it possible to format all documents in the workspace?

**Comment by deviousasti** [comment]
This extension serves as the formatting command handler for VS (for F# content files).
VS doesn't have a format all documents command (for any language).

This sort of action is generally reserved for a build task though.

**Comment by brettrowberry** [comment]
When you say build task, do you mean like a CI step or something in an .fsproj file? Any examples?

**Comment by deviousasti** [comment]
Like a FAKE build task. Fantomas has a set of helpers for this:
https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/FakeHelpers.fs

Something like this:

```
Directory.EnumerateFiles(".\\", "*.fs", SearchOption.AllDirectories) 
|> formatFilesAsync 
|> Async.RunSynchronously
```
