### ISSUE TITLE
Formatting differs in VS from online fantomas even though I didn't touch the defaults

### ISSUE THREAD

**Issue by Chiel92** [deviousasti/fsharp-formatting-for-vs#8]
Hi

When trying to format the following code in the [online formatter](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAHAkgOYB2sATonmALxUB8dtAZgK7FgD6YAtHWK%2BwoBnHLzABlFtGiIhQsAAoFASgA0YYVmUAdMtuKYcuAPK4sAS1jtcNRTYbM2G2S3Si%2BuAErYWZdgB4AHwlYAFtKYVctMCCPbyxfdgA5K0RdfUMwdFhYAGsAQQALRABDeDsUAAUSsiFEMn8AchK6ZUVzYlwWLBR8Tu626nT2CDswB34nLjEBTh4%2BSWlZeSU1MA6urTaN7uHIVXAoOqwLYkIhVDAAbUOIUFHRyAASLABPXGQ0SA6sfdvHp4ANxK6BYn2u-weAAYDg8HpA%2BkhiFhxOYAF7IWFwiAAFkhYAAuv8AL5Yu7455vD6Xb7Iv7Y57A0Hgm7YiAARjJcMgAFkSgAPAAyHUQgsQZywhXpbPZACYofiiQ9Sf97tyXu9wZAAEY5dDS%2BFAkFgy6stmyrnw8SIULmODZYj5LAAUWI8GMTGFxEx%2BIgTBBdUVJK5asNVK1utg%2BstUCNzNNvrAAGYYxBIOJcCUZAAhRBMciIapkErhLD1A1wrBkMFB5Uhika6lfSPRhtMk1oM3YnGpqAZrOIXP5iiC2AAd3q0BKdT6gNgU4sVgrDyrNexStGKoeoYB4ZpLeXsfbLMTAFZe%2BnMzm8wWAKq4D5kKcz4hzheWYiHv0BxC1zf1hlGwjPVD0ZY0TzZMAADYL37a9h0QABhdBpyERCrBEatoCwcgv34H8-wgLdRh3NMgP3ECYzA%2BNO0TAB2WCr0HG8KB5G1tXLXt-XQQN12DVUGz3ZtKLbcCE0ggAORiByHAt0IdPDuN4uENyIgD1SEqADyouMOwhSCAE5pJkfImDLMh0NCUISjw1dfz4usBMAzSdREwDj3EmUYUTS8ZJYxBrVte0ly4giHP-JyNM1Cio1A3SIJlTkfLgxBTPMwK7SjELEzswiwGI8lnOi4TYp0jzaMguUL0RcUsGMYgABUyFeAB1cxJUUsKVP47dBOKrS3PVcr9JlFNkqY-IyFgNh4AAEUQdBzFtczbOrezusc3qiqbKAfji4auzhdkex8vl%2BXwJgGuKYhnR4gLCnILA2vgDrexxBVwrUyKw362lfjKsSKplc9ToFPomHMflTHqEocLIZ1%2BVwYQhA-PDTw%2BjaIq2qKdr%2B-bAZG7F2Rg0H%2BW8OAyHgZ7XsTd68oKsBSNjFy9oBmjCaOhjSfJ8h4CSFhQg4sgPXwMtQguXt2Xp9Sftx0IonMRbvQAMXIayTnqBrorZvTDoedkpJ8nnKZ5BWlcQVWyHVlaL2gQoaizcyODHcwXqlaXvt3X7WdE9m9dGdkjNJybi1eYwyGFERqalN6MYeVT8plr3cZ99yCf9iB5QvM6Q5KMOI-MER%2BcF%2BoRbFiXEylz7E89siXPltxFZFS3rc17Xfd1xNZSSyDIFz-PI6wU3G-NlvYZtny7Yd7D6md12Oo97HZa1VOhvTruLVJgA1cDsw6eAOkIaO8Lp6uGaZylvbpHWEuxWUxt7s7lbYbCPz3t1D%2BP2PF5IvqU%2Bvjut84SyhOo-AUs1YBYAAOLYARkjZYH4v5njjqMBO58-7AVKoAzyd8QaPzNiKbM2RoC5GzMWEh2AhD1XECWJCUYBaflCndH%2BhUcaYNbGnP2XcSa9ySIgMc5tcxYAnOKLWHx5oQ2IO1D8%2BQ3RsRLrUTqzCz5Jzrr9bS2CgZ3y5r3AA0ogRABBLrXT6DQ8IXofSQSUuteOPVf7bRXgAzhndIKykNmA-kt1bRCEKEgyCp9MZfSXsndh%2BMuGuKDr3VEZxMCTUIALWqLVEDah5AgSxbJrEsMZhgmKHC17hLZEmbyvd8iLRIM-Ygr8rCohILDXwiAGqwBqsiWGqMmHKVsZtexbDclhJcYUnubI%2B5uHqMQVpgJRRWEIPIoWEiOjSIwkojpqC7GsOXr0m%2BOC4RJk3lEqsdoh5pKWTYlZypDgEixN8IQysUaXEycSIAA)

```fs
let pIgnore p = p >>= fun _ -> fun rest -> Success ((), rest)
let pOption p = (p >>= fun result -> pReturn <| Some result) <|> pReturn None
let lookAhead (p:Parser<'a>) (input:Input) =
    (p >>= fun _ -> fun _ -> Success ((), input)) input
```

the result looks like 

```fs
let pIgnore p =
    p >>= fun _ -> fun rest -> Success((), rest)

let pOption p =
    (p >>= fun result -> pReturn <| Some result)
    <|> pReturn None

let lookAhead (p: Parser<'a>) (input: Input) =
    (p >>= fun _ -> fun _ -> Success((), input)) input
```

However when I try it in VS using this plugin I get

```fs
let pIgnore p =
    p
    >>= fun _ -> fun rest -> Success((), rest)

let pOption p =
    (p
     >>= fun result -> pReturn <| Some result)
    <|> pReturn None

let lookAhead (p: Parser<'a>) (input: Input) =
    (p
     >>= fun _ -> fun _ -> Success((), input)) input
```

which looks really odd. I didn't change the defaults, and even after explicitly adding the editorconfig with default values the behaviour stayed the same. Any idea what might be going wrong?

**Comment by deviousasti** [comment]
The nicer formatting is generated only by the latest release of Fantomas which breaks formatting options and needs some work to patch through.

I've done most of the work - I'll try to ship today.

**Comment by deviousasti** [comment]
I've released an update. 
Could you try it out?

**Comment by Chiel92** [comment]
Great, it seems to work nicely now! Thanks
